template=/cpp-info111/template/wims.pl
template=/cpp-info111/exercices_src/attic/metadata.pl
@ /cpp-info111/exercices_src/attic/procedure_bof_calling_1.cpp
@ /cpp-info111/exercices_src/attic/procedure_bof_calling_2.cpp
@ /cpp-info111/exercices_src/attic/procedure_bof_calling_2a.cpp
@ /cpp-info111/exercices_src/attic/procedure_bof_calling_3.cpp
@ /cpp-info111/exercices_src/attic/procedure_bof_calling_4.cpp
@ /cpp-info111/exercices_src/attic/procedure_bof_math_4.cpp
@ /cpp-info111/exercices_src/attic/struct_bof_fonction_1.cpp
@ /cpp-info111/exercices_src/attic/struct_bof_fonction_2.cpp
@ /cpp-info111/exercices_src/attic/struct_bof_fonction_3.cpp
@ /cpp-info111/exercices_src/attic/vector1D_1_input.cpp
@ /cpp-info111/exercices_src/attic/vector1D_3_input.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche1a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche1b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche1c.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche2a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche2b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche2c.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche3a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche3b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche3c.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche4a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche4b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche4c.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche5a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche5b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche5c.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche6a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche6b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche6c.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche7a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche7b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_recherche7c.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_1a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_1b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_1c.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_2a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_2b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_2c.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_3a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_3b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_3c.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_4a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_4b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_4c.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_5a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_5b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_5c.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_6a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_6b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_6c.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_7a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_7b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_7c.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_8a.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_8b.cpp
@ /cpp-info111/exercices_src/attic/vector1D_tri_8c.cpp
